dieta/urls.py
from django.urls import path
from . import views

app_name = 'dieta'

urlpatterns = [
    path('criar_dieta/', views.criar_dieta, name='criar_dieta'),
    path('editar_dieta/<int:dieta_id>/', views.editar_dieta, name='editar_dieta'),
    path('excluir_dieta/<int:dieta_id>/', views.excluir_dieta, name='excluir_dieta'),
    path('atualizar_calorias/<int:dieta_id>/', views.atualizar_calorias, name='atualizar_calorias'),
    path('lista_dietas/', views.lista_dietas, name='lista_dietas'),
    path('definir_meta_calorias/', views.definir_meta_calorias, name='definir_meta_calorias'),

]

setup/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('healthy.urls')),
    path('goals/', include('goals.urls')),

    path('treino/', include('treino.urls')),
    path('dieta/', include('dieta.urls', namespace='dieta')),
    path('calculos/', include('calculos.urls', namespace='calculos')),
    path('registro/', include('registro.urls')),

    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

treino/urls.py
from django.urls import path

from . import views

app_name = 'treino'

urlpatterns = [
    path('', views.index, name='index'),
    path('dia/<str:dia_da_semana>/', views.dia, name='dia'),
    path('editar/<str:dia_da_semana>/', views.editar_treino, name='editar_treino'),
    path('excluir/<str:dia_da_semana>/', views.excluir_treino, name='excluir_treino'),
    path('salvar/<str:dia_semana>/', views.salvar_treino, name='salvar')

]

treino/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Treino(models.Model):
    dia_da_semana = models.CharField(max_length=10)
    texto = models.TextField()
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    editavel = models.BooleanField(default=True)

    def __str__(self):
        return self.dia_da_semana

treino/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound
from treino.models import Treino
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    treinos = {
        'segunda': None,
        'terça': None,
        'quarta': None,
        'quinta': None,
        'sexta': None,
        'sábado': None,
        'domingo': None
    }

    treinos_existentes = Treino.objects.filter(usuario=request.user)
    for treino in treinos_existentes:
        treinos[treino.dia_da_semana] = treino

    return render(request, 'treino/index.html', {'treinos': treinos})

@login_required
def dia(request, dia_da_semana):
    try:
        treino = Treino.objects.get(dia_da_semana=dia_da_semana, usuario=request.user)
    except Treino.DoesNotExist:
        treino = Treino(dia_da_semana=dia_da_semana, usuario=request.user)

    if request.method == 'POST':
        treino.texto = request.POST['texto']
        treino.save()
        return redirect('treino:index')

    return render(request, 'treino/dia.html', {'treino': treino})

@login_required
def editar_treino(request, dia_da_semana):
    try:
        treino = Treino.objects.get(dia_da_semana=dia_da_semana, usuario=request.user)
        if not treino.editavel:
            return HttpResponseNotFound("Treino não é editável.")
    except Treino.DoesNotExist:
        return HttpResponseNotFound("Treino não encontrado.")

    if request.method == 'POST':
        treino.texto = request.POST['texto']
        treino.save()
        return redirect('treino:index')

    return render(request, 'treino/editar_treino.html', {'treino': treino})

@login_required
def excluir_treino(request, dia_da_semana):
    try:
        treino = Treino.objects.get(dia_da_semana=dia_da_semana, usuario=request.user)
        if not treino.editavel:
            return HttpResponseNotFound("Treino não é editável.")
    except Treino.DoesNotExist:
        return HttpResponseNotFound("Treino não encontrado.")

    if request.method == 'POST':
        treino.delete()
        return redirect('treino:index')

    return render(request, 'treino/excluir_treino.html', {'treino': treino})

@login_required
def salvar_treino(request, dia_semana=None):
    if request.method == 'POST':
        texto = request.POST['texto']

        if dia_semana:
            try:
                treino = Treino.objects.get(dia_da_semana=dia_semana, usuario=request.user)
                treino.texto = texto
            except Treino.DoesNotExist:
                treino = Treino(dia_da_semana=dia_semana, texto=texto, usuario=request.user)
        else:
            pass

        treino.save()
        return redirect('treino:index')
    else:
        return redirect('treino:index')
    
    

templates/treino/dia.html
{% extends  'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Dias da senana{% endblock %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/treino.css' %}">
</head>

<body>
  <section class="ContainerList">
    <div class="boxList">

    <h1 class="title-listar">{{ treino.dia_da_semana }}</h1>

    <form action="{% url 'treino:salvar' dia_semana=treino.dia_da_semana %}" method="post">
        {% csrf_token %}
        <p class="title-planner">Planeje seu treino:</p>
        <div>
            <textarea class="width-area" name="texto">{{ treino.texto }}</textarea>
        </div>
        <div>
            <input class="saveButton" type="submit" value="Salvar">
            <input class="editButton" type="submit" value="Editar" name="editar">
        </div>
    </form>

    </div>
    </div>
</section>
</body>
{% endblock %}

templates/treino/editar_treino.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Treino - {{ treino.dia_da_semana }}{% endblock %}

{% block content %}
<head>
  <link rel="stylesheet" href="{% static 'css/treino.css' %}">
</head>


<body>
  <section class="ContainerList">
    <div class="boxList">
      <h1 class="title-listar">Editar Treino: {{ treino.dia_da_semana }}</h1>

      <form method="post">
        {% csrf_token %}
        <div class="editTreino">
          <label class="title-planner" for="texto">Treino:</label>
          <textarea class="width-area" id="texto" name="texto">{{ treino.texto }}</textarea>
        </div>

        <input class="saveButton" type="submit" value="Salvar">
        <a class="cancelButton" href="{% url 'treino:index' %}">Cancelar</a>
      </form>

  </div>
</section>
</body>
 
{% endblock %}

templates/treino/excluir_treino.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Excluir Treino - {{ treino.dia_da_semana }}{% endblock %}

{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/treino.css' %}">
</head>

<body>
  <section class="ContainerList">
    <div class="boxList">
      <h1 class="title-listar">Excluir Treino - {{ treino.dia_da_semana }}</h1>
      <p class="title-planner">Tem certeza de que deseja excluir o treino?</p>
      <form method="post">
        {% csrf_token %}
        <button class="saveButton" type="submit">Sim, Excluir.</button>
        <a class="cancelButton" href="{% url 'treino:index' %}">Cancelar</a>
      </form>
    </div>
  </section>
</body>
 
{% endblock %}

templates/treino/index.html
{% extends  'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Dias da senana{% endblock %}

{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/treino.css' %}">
</head>

<body>

  <section class="ContainerList">
    <div class="boxList">
    <h1 class="title-listar">Lista de Treinos</h1>
    
      <p class="day-week">
        {% for dia_semana, treino in treinos.items %}
          <p class="title-week">
            {{ dia_semana|title }}:
            {% if treino %}
              <a class="seeDetails" href="{% url 'treino:dia' dia_semana %}">Ver Detalhes</a>
              <a class="edit" href="{% url 'treino:editar_treino' dia_semana %}">Editar</a>
              <a class="delete" href="{% url 'treino:excluir_treino' dia_semana %}">Excluir</a>
            {% else %}
              <a class="addTreino" href="{% url 'treino:dia' dia_semana %}">Adicionar Treino</a>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    </div>
   
    </div>
  </section>
</body>
{% endblock %}