dieta/urls.py
from django.urls import path
from . import views

app_name = 'dieta'

urlpatterns = [
    path('criar_dieta/', views.criar_dieta, name='criar_dieta'),
    path('editar_dieta/<int:dieta_id>/', views.editar_dieta, name='editar_dieta'),
    path('excluir_dieta/<int:dieta_id>/', views.excluir_dieta, name='excluir_dieta'),
    path('atualizar_calorias/<int:dieta_id>/', views.atualizar_calorias, name='atualizar_calorias'),
    path('lista_dietas/', views.lista_dietas, name='lista_dietas'),
    path('definir_meta_calorias/', views.definir_meta_calorias, name='definir_meta_calorias'),

]

registro/urls.py
from django.urls import path
from . import views

app_name = 'registro'

urlpatterns = [
    path('listar_registros/', views.listar_registros, name='listar_registros'),
    path('criar_registro/', views.criar_registro, name='criar_registro'),
    path('editar_registro/<int:registro_id>/', views.editar_registro, name='editar_registro'),
    path('excluir_registro/<int:registro_id>/', views.excluir_registro, name='excluir_registro'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('healthy.urls')),
    path('goals/', include('goals.urls')),

    path('treino/', include('treino.urls')),
    path('dieta/', include('dieta.urls', namespace='dieta')),
    path('calculos/', include('calculos.urls', namespace='calculos')),
    path('registro/', include('registro.urls')),

    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registro/models.py
from django.db import models
from django.contrib.auth.models import User

class RegistroDiario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateField()
    nota = models.TextField()

    def __str__(self):
        return f"Registro de {self.user.username} em {self.data}"

registro/views.py
from django.shortcuts import render, redirect
from .models import RegistroDiario
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest

@login_required
def listar_registros(request):
    registros = RegistroDiario.objects.filter(user=request.user)
    return render(request, 'registro/listar_registros.html', {'registros': registros})

@login_required
def criar_registro(request):
    if request.method == 'POST':
        data = request.POST.get('data')
        nota = request.POST.get('nota')

        if not data or not nota:
            return HttpResponseBadRequest("Campos em branco não são permitidos.")

        RegistroDiario.objects.create(user=request.user, data=data, nota=nota)
        return redirect('registro:listar_registros')

    return render(request, 'registro/criar_registro.html')

@login_required
def editar_registro(request, registro_id):
    try:
        registro = RegistroDiario.objects.get(pk=registro_id, user=request.user)
    except RegistroDiario.DoesNotExist:
        return HttpResponseBadRequest("Registro não encontrado.")

    if request.method == 'POST':
        data = request.POST.get('data')
        nota = request.POST.get('nota')

        if not data or not nota:
            return HttpResponseBadRequest("Campos em branco não são permitidos.")

        registro.data = data
        registro.nota = nota
        registro.save()
        return redirect('registro:listar_registros')
    else:
        context = {'registro': registro}
        return render(request, 'registro/editar_registro.html', context)

@login_required
def excluir_registro(request, registro_id):
    try:
        registro = RegistroDiario.objects.get(pk=registro_id, user=request.user)
    except RegistroDiario.DoesNotExist:
        return HttpResponseBadRequest("Registro não encontrado.")

    registro.delete()
    return redirect('registro:listar_registros')

templates/registro/criar_registro.html
{% extends 'base.html' %}
{% block title %}Criar Registro{% endblock %}

{% block content %}

<head>
    <style>
        body {
            padding-bottom: 100px;
        }

        .ContainerRegistro {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .boxRegistro {
            background-color: rgb(105, 128, 110);
            width: 80%;
            border-radius: 20px;
            padding: 30px;
        }

        .title-listar {
            color: rgb(220, 246, 242);
        }

        .labelRegistro {
            color: black;
            font-weight: 500;
            font-size: 20px;
        }

        .box-form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            padding-bottom: 10px;
        }

        .input {
            border-radius: 10px;
            border-color: aliceblue;
        }

        .buttonNew {
            background-color: rgb(22, 216, 103);
            width: 20%;
            text-align: center;
            color: black;
            border-radius: 10px;
            height: 40px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-weight: 500;
        }

        .descriptionButton {
            color: black;
            text-align: center;
            font-weight: 500;
        }

    </style>
</head>

<body>
    <section class="ContainerRegistro">
        <div class="boxRegistro">

            <div class="title-listar">
                <h1>Criar Registro</h1>
            </div>

            <div class="form-registro">
                <form method="post">
                    {% csrf_token %}

                    <div class="box-form">
                        <label class="labelRegistro" for="id_data">Data:</label>
                        <input type="date" id="id_data" name="data" class="input" required>
                    </div>

                    <div class="box-form">
                        <label class="labelRegistro" for="id_nota">Nota:</label>
                        <textarea id="id_nota" name="nota" rows="4" cols="50" class="input" required></textarea>
                    </div>

                    <div class="box-form">
                        <input type="submit" class="buttonNew" value="Salvar Registro">
                    </div>
                </form>
                <div class="box-form">
                    <a class="descriptionButton" href="{% url 'registro:listar_registros' %}">Voltar para a lista de registros</a>
                </div>

            </div>
        </div>

    </section>
</body>
{% endblock %}

templates/registro/editar_registro.html
{% extends 'base.html' %}
{% block title %}Editar Registro{% endblock %}

{% block content %}

<head>
    <style>
        body {
            padding-bottom: 100px;
        }

        .ContainerRegistro {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .boxRegistro {
            background-color: rgb(105, 128, 110);
            width: 80%;
            border-radius: 20px;
            padding: 30px;
        }

        .title-listar {
            color: rgb(220, 246, 242);
        }

        .labelRegistro {
            color: black;
            font-weight: 500;
            font-size: 20px;
        }

        .box-form {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            padding-bottom: 10px;
        }

        .input {
            border-radius: 10px;
            border-color: aliceblue;
        }

        .buttonNew {
            background-color: rgb(22, 216, 103);
            width: 20%;
            text-align: center;
            color: black;
            border-radius: 10px;
            height: 40px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-weight: 500;
        }

        .descriptionButton {
            color: black;
            text-align: center;
            font-weight: 500;
        }

    </style>
</head>

<body>
    <section class="ContainerRegistro">
        <div class="boxRegistro">

            <div class="title-listar">
                <h1>Editar Registro</h1>
            </div>
            <div class="form-registro">
                <form method="post">
                    {% csrf_token %}
                    <div class="box-form">
                        <label for="data">Data:</label>
                        <input type="date" id="data" name="data" value="{{ registro.data }}" class="data-input" required>
                    </div>

                    <div class="box-form">
                        <label for="nota">Nota:</label>
                        <textarea id="nota" name="nota" class="nota-input" rows="4" cols="50" required>{{ registro.nota }}</textarea>
                    </div>

                    <div class="box-form">
                        <input type="submit" class="buttonNew" value="Salvar Alterações">
                    </div>

                </form>
            </div>
            <div class="box-form">
                <a class="descriptionButton" href="{% url 'registro:listar_registros' %}">Voltar para a lista de registros</a>
            </div>
        </div>
    </section>
</body>

{% endblock %}

templates/registro/listar_registros.html
{% extends 'base.html' %}
{% block title %}Lista de Registros{% endblock %}
{% block content %}
<head>
    <style>
        .ContainerList {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .boxList {
            background-color: rgb(105, 128, 110);
            width: 80%;
            min-height: 300px;
            border-radius: 20px;
            padding: 30px;
        }
        .buttonNew {
            background-color: rgb(22, 216, 103);
            width: 20%;
            text-align: center;
            color: rgb(44, 115, 177);
            border-radius: 30px;
            height: 40px;
            display: flex;
            justify-content: center; /* Center align horizontally */
            align-items: center; /* Center align vertically */
        }
        .buttonNew2 {
            background-color: #49aca0;
            width: 20%;
            text-align: center;
            color: rgb(44, 115, 177);
            border-radius: 30px;
            height: 40px;
            display: flex;
            justify-content: center; /* Center align horizontally */
            align-items: center; /* Center align vertically */
        }

        .title-listar {
            color:  rgb(220, 246, 242);
        }

        .descriptionButton {
            text-decoration: none;
            color: black;
            text-align: center;
            font-weight: 500;
        }
        .teste {
            padding-bottom: 10px;
        }

        .editButton {
            background-color: #49aca0;
            color: black;
            font-weight: 400;
            padding: 10px;
        }

        .excButton {
            background-color: #e05147;
            color: black;
            font-weight: 400;
            padding: 10px;
        }
        .spaceDiet {
            padding: 10px;
        }

        .registroTitle {
            font-weight: 500;
            color: black;
            text-decoration: none;
        }
    </style>
</head>

<body>
    <section class="ContainerList" >
        <div class="boxList">
            <h1 class="title-listar">Registros Diários</h1>
            <div class="teste">
                <ul>
                    {% for registro in registros %}
                        <li class="spaceDiet">
                            <a class="editButton" href="{% url 'registro:editar_registro' registro.id %}">Visualizar</a>
                            <a class="excButton" href="{% url 'registro:excluir_registro' registro.id %}" onclick="return confirm('Tem certeza que deseja excluir este registro?')">Excluir</a>
                            Data: <a class="registroTitle">{{ registro.data }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="buttonNew">
                <a class="descriptionButton" href="{% url 'registro:criar_registro' %}">Criar Novo Registro</a>
            </div>
        </div>
    </section>
</body>
{% endblock %}