dieta/urls.py
from django.urls import path
from . import views

app_name = 'dieta'

urlpatterns = [
    path('criar_dieta/', views.criar_dieta, name='criar_dieta'),
    path('editar_dieta/<int:dieta_id>/', views.editar_dieta, name='editar_dieta'),
    path('excluir_dieta/<int:dieta_id>/', views.excluir_dieta, name='excluir_dieta'),
    path('atualizar_calorias/<int:dieta_id>/', views.atualizar_calorias, name='atualizar_calorias'),
    path('lista_dietas/', views.lista_dietas, name='lista_dietas'),
    path('definir_meta_calorias/', views.definir_meta_calorias, name='definir_meta_calorias'),

]

setup/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('healthy.urls')),
    path('goals/', include('goals.urls')),

    path('treino/', include('treino.urls')),
    path('dieta/', include('dieta.urls', namespace='dieta')),
    path('calculos/', include('calculos.urls', namespace='calculos')),
    path('registro/', include('registro.urls')),

    path('', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dieta/models.py
from django.db import models
from django.contrib.auth.models import User

class Dieta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.TextField(default="Qual Refeição")
    notas = models.TextField()
    calorias = models.IntegerField()

    def __str__(self):
        return self.user.username + "'s Dieta"
    
class CaloriasMeta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    meta_diaria = models.IntegerField()

    def __str__(self):
        return f"Meta de calorias diárias de {self.user}: {self.meta_diaria} calorias"

dieta/views.py
from django.shortcuts import render, redirect
from .models import Dieta, CaloriasMeta
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest

@login_required
def criar_dieta(request):
    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        notas = request.POST.get('notas')
        calorias = request.POST.get('calorias')

        if not titulo or not notas or not calorias:
            return HttpResponseBadRequest("Campos em branco não são permitidos.")

        Dieta.objects.create(user=request.user, titulo=titulo, notas=notas, calorias=calorias)
        return redirect('dieta:lista_dietas')
    return render(request, 'dieta/criar_dieta.html')

@login_required
def editar_dieta(request, dieta_id):
    try:
        dieta = Dieta.objects.get(pk=dieta_id, user=request.user)
    except Dieta.DoesNotExist:
        return HttpResponseBadRequest("Dieta não encontrada.")

    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        notas = request.POST.get('notas')
        calorias = request.POST.get('calorias')

        if not titulo or not notas or not calorias:
            return HttpResponseBadRequest("Campos em branco não são permitidos.")

        dieta.titulo = titulo
        dieta.notas = notas
        dieta.calorias = calorias
        dieta.save()
        return redirect('dieta:lista_dietas')
    else:
        # Preencha o contexto com os valores existentes da dieta
        context = {
            'dieta': dieta,
        }
        return render(request, 'dieta/editar_dieta.html', context)

@login_required
def excluir_dieta(request, dieta_id):
    try:
        dieta = Dieta.objects.get(pk=dieta_id, user=request.user)
    except Dieta.DoesNotExist:
        return HttpResponseBadRequest("Dieta não encontrada.")

    dieta.delete()
    return redirect('dieta:lista_dietas')

@login_required
def atualizar_calorias(request, dieta_id):
    try:
        dieta = Dieta.objects.get(pk=dieta_id, user=request.user)
    except Dieta.DoesNotExist:
        return HttpResponseBadRequest("Dieta não encontrada.")

    if request.method == 'POST':
        calorias = request.POST.get('calorias')

        if not calorias:
            return HttpResponseBadRequest("Campo em branco não é permitido.")

        dieta.calorias = calorias
        dieta.save()

    return redirect('dieta:lista_dietas')

@login_required
def lista_dietas(request):
    dietas = Dieta.objects.filter(user=request.user)
    calorias_meta = CaloriasMeta.objects.filter(user=request.user).first()


    return render(request, 'dieta/lista_dietas.html', {'dietas': dietas, 'calorias_meta': calorias_meta})

@login_required
def definir_meta_calorias(request):
    calorias_meta = CaloriasMeta.objects.filter(user=request.user).first()

    if request.method == "POST":
        meta_diaria = request.POST.get("calorias_meta")

        if calorias_meta is not None:
            calorias_meta.meta_diaria = meta_diaria
            calorias_meta.save()
        else:
            calorias_meta = CaloriasMeta(user=request.user, meta_diaria=meta_diaria)
            calorias_meta.save()

        return redirect('dieta:lista_dietas')

    return render(request, 'dieta/definir_meta_calorias.html', {'calorias_meta': calorias_meta})

templates/dieta/atualizar_calorias.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Atualizar Calorias{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Atualizar Calorias</title>
</head>
<body>
    <h1>Atualizar Calorias da Dieta</h1>
    <form method="post">
        {% csrf_token %}
        <label for="calorias">Calorias:</label>
        <input type="number" name="calorias" value="{{ dieta.calorias }}">
        <input type="submit" value="Atualizar">
    </form>
    <a href="{% url 'dieta:lista_dietas' %}">Voltar para a lista de dietas</a>
</body>
</html>
{% endblock %}

templates/dieta/criar_dieta.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Criar Dieta{% endblock %}

{% block content %}

<head>
    <style>
        body{
            padding-bottom: 100px;
        }
       .ContainerDieta{
        display: flex;
        align-items: center;
        justify-content: center;
       }
       .boxDieta{
        background-color: rgb(105, 128, 110);
        width: 80%;
        
        border-radius: 20px;
        padding: 30px;
       }
       .title-listar {
        color:  rgb(220, 246, 242);
        }
        .labelDieta{
            color: black;
            font-weight: 500;
            font-size: 20px;
        }
        .box-form{
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            padding-bottom: 10px;
        }
        .input{
          border-radius: 10px;
          border-color: aliceblue;
        }
        .buttonNew {
        background-color: rgb(22, 216, 103);
        width: 20%;
        text-align: center;
        color: black; 
        border-radius: 10px;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;
        font-weight: 500
    }

.descriptionButton {
    color: black;
    text-align: center;
    font-weight: 500;
}

    </style>
</head>
<body>
    <section class="ContainerDieta">
        <div class="boxDieta">

        
        <div class="title-listar">
            <h1>Criar Dieta</h1>
        </div>
        
        <div class="form-dieta">
            <form method="post">
                {% csrf_token %}

                <div class="box-form">
                    <label class="labelDieta" for="id_titulo">Título:</label>
                    <input type="text" id="id_titulo" name="titulo" class="input" required>
                </div>
                
                <div class="box-form">
                <label class="labelDieta" for="id_notas">Notas:</label>
                <textarea id="notas" name="notas" rows="4" cols="50" class="input" required></textarea>
                </div>

                <div class="box-form">
                    <label  class="labelDieta" for="id_calorias">Calorias:</label>
                    <input type="number" id="id_calorias" name="calorias" class="input" required>
                </div>
               
                <div class="box-form">
                    <input type="submit" class="buttonNew" value="Salvar Dieta">
                </div>
            </form>
            <div class="box-form">
                <a class="descriptionButton" href="{% url 'dieta:lista_dietas' %}">Voltar para a lista de dietas</a>
            </div>
           
        </div> 
    </div>

    </section>
</body>
{% endblock %}

templates/dieta/definir_meta_calorias.html
{% extends "base.html" %}
{% load static %}
{% block title %}Definir Meta de Calorias Diárias{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/metas.css' %}">
<div class="containerGeral">
  <div class="container">
    <h1>Definir Meta de Calorias Diárias</h1>
    {% if calorias_meta %}
        <div>
            <p>Sua meta diária de calorias é de {{ calorias_meta.meta_diaria }} calorias.</p>
            <p>Editar meta:</p>
        </div>
    {% else %}
        <div>
            <p>Você ainda não definiu uma meta diária de calorias.</p>
            <p>Definir meta:</p>
        </div>
    {% endif %}
    <form method="post" action="{% url 'dieta:definir_meta_calorias' %}">
        {% csrf_token %}
        <div>
            <input class="input" type="number" name="calorias_meta" id="calorias_meta" placeholder="Meta diária de calorias">
            <input class="salvar" type="submit" value="Salvar">
        </div>
    </form>
</div>
</div>
</div>
{% endblock %}

templates/dieta/editar_dieta.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Editar Dieta{% endblock %}

{% block content %}
<head>
    <style>
        body{
            padding-bottom: 100px;
        }
       .ContainerDieta{
        display: flex;
        align-items: center;
        justify-content: center;
       }
       .boxDieta{
        background-color: rgb(105, 128, 110);
        width: 80%;
        
        border-radius: 20px;
        padding: 30px;
       }
       .title-listar {
        color:  rgb(220, 246, 242);
        }
        .labelDieta{
            color: black;
            font-weight: 500;
            font-size: 20px;
        }
        .box-form{
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            padding-bottom: 10px;
        }
        .input{
          border-radius: 10px;
          border-color: aliceblue;
        }
        .buttonNew {
        background-color: rgb(22, 216, 103);
        width: 20%;
        text-align: center;
        color: black; 
        border-radius: 10px;
        height: 40px;
        display: flex;
        justify-content: center;
        align-items: center;
        font-weight: 500
    }

.descriptionButton {
    color: black;
    text-align: center;
    font-weight: 500;
}

    </style>
</head>

<body>
    <section class="ContainerDieta">
        <div class="boxDieta">

            <div class="title-listar">
            <h1>Editar Dieta</h1>
            </div>
            <div class="form-dieta">
                <form method="post">
                    {% csrf_token %}
                    <div class="box-form">
                        <label for="titulo">Título:</label>
                        <input type="text" id="titulo" name="titulo" value="{{ dieta.titulo }}" class="titulo-input" required>
                    </div>

                    <div class="box-form">
                        <label for="notas">Notas:</label>
                        <textarea id="notas" name="notas" class="notas-input" rows="4" cols="50" required>{{ dieta.notas }}</textarea>
                    </div>

                    <div class="box-form">
                        <label for="calorias">Calorias:</label>
                        <input type="number" id="calorias" name="calorias" value="{{ dieta.calorias }}" required>
                    </div>
                
                    <div class="box-form">
                        <input type="submit" class="buttonNew" value="Salvar Alterações">
                    </div>
                    
                </form>
            </div>
            <div class="box-form">
                <a  class="descriptionButton" href="{% url 'dieta:lista_dietas' %}">Voltar para a lista de dietas</a>
            </div>
        </div>
    </section>
</body>

{% endblock %}

templates/dieta/lista_dietas.html
{% extends 'base.html' %}
{% block title %}Lista de Dietas{% endblock %}
{% block content %}
<head>
    <style>
        .ContainerList {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .calorias_meta{
            color:  rgb(246, 246, 246);
        }

        .boxList {
            background-color: rgb(105, 128, 110);
            width: 80%;
            min-height: 300px;
            border-radius: 20px;
            padding: 30px;
        }
        .buttonNew {
            background-color: rgb(22, 216, 103);
            width: 20%;
            text-align: center;
            color: rgb(44, 115, 177);
            border-radius: 30px;
            height: 40px;
            display: flex;
            justify-content: center; /* Center align horizontally */
            align-items: center; /* Center align vertically */
        }
        .buttonNew2 {
            background-color: #49aca0;
            width: 20%;
            text-align: center;
            color: rgb(44, 115, 177);
            border-radius: 30px;
            height: 40px;
            display: flex;
            justify-content: center; /* Center align horizontally */
            align-items: center; /* Center align vertically */
        }

        .title-listar {
            color:  rgb(220, 246, 242);
        }

        .descriptionButton {
            text-decoration: none;
            color: black;
            text-align: center;
            font-weight: 500;
        }
        .teste{
            padding-bottom: 10px;
        }

        .editButton{
            background-color: #49aca0;
            color: black;
            font-weight: 400;
            padding: 10px;
        }

        .excButton{
            background-color: #e05147;
            color: black;
            font-weight: 400;
            padding: 10px;
        }
        .spaceDiet{
            padding: 10px;
        }

        .dietTitle{
            font-weight: 500;
            color: black;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <section class="ContainerList" >
        <div class="boxList">
            <h1 class="title-listar">Dietas Planejadas</h1>
            <div class="teste">
                <h5 class="calorias_meta">Meta Diária de Calorias: {% if calorias_meta %}{{ calorias_meta.meta_diaria }}{% else %}Não definida{% endif %} calorias</h5>
                <ul>
                    {% for dieta in dietas %}
                        <li class="spaceDiet">
                            <a class="editButton" href="{% url 'dieta:editar_dieta' dieta.id %}">Visualizar</a> 
                            <a class="excButton" href="{% url 'dieta:excluir_dieta' dieta.id %}" onclick="return confirm('Tem certeza que deseja excluir esta dieta?')">Excluir</a>
                            A Refeição: <a class="dietTitle">{{ dieta.titulo }}</a>, possui ({{ dieta.calorias }} calorias).
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="buttonNew">
                <a class="descriptionButton" href="{% url 'dieta:criar_dieta' %}">Criar Nova Refeição</a>
                
            <br><br>
            </div>
            <div class="buttonNew2">
                <a class="descriptionButton" href="{% url 'dieta:definir_meta_calorias' %}">Definir Meta de Calorias</a>
                
            </div>
            
        </div>
    </section>
</body>
{% endblock %}